global:
  scrape_interval: 15s

  external_labels:
    monitor: 'lf-monitor'

scrape_configs:
  - job_name: 'lightningfilter'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 1s
    static_configs:
      - targets: ['telegraf:9273']
