[package]
name = "lf-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
ctrlc = "3.4.5"
nickel = "0.11.0"
prometheus-client = "0.19.0"
serde = "1.0.210"
serde_json = "1.0.127"
uds = "0.4.2"
