name: Build and Cache Docker Images

on:
  push:
    branches: ["open-source"]
  pull_request:
    branches: ["open-source"]

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
