name: Docker Image CI

on:
  push:
    branches: [ "open-source" ]
  pull_request:
    branches: [ "open-source" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build the Docker image
      run: docker build . --file Dockerfile --target lf-developer --tag lf-developer:$(date +%s)
